### ISSUE TITLE
Set up `lerna` and add more generators

### ISSUE THREAD

**Issue by grabbou** [callstack-io/generator-node-module#1]
We need to open source our layouts for `react-native` applications as well. We can probably base them on the `node-module` generator.

**Comment by zamotany** [comment]
Also generator with typescript instead of flow

**Comment by grabbou** [comment]
Yeah, I think it's a nice idea. Looking forward to your ideas how to move
it forward!

**Comment by satya164** [comment]
Do we need lerna right now? Maybe worth waiting for yarn workspaces?

**Comment by zamotany** [comment]
@satya164 need lerna or other generators??

**Comment by satya164** [comment]
lerna

**Comment by zamotany** [comment]
I don't believe yarn workspaces will happen soon, they've only done 1 phase out of 5 and I'm not sure we can wait for it more than a week.

**Comment by krizzu** [comment]
If we're going with Lerna then, what `mode` should we apply to a repo?
I'd say to go with `Independent mode` as it would allow to manage generators independently of each other, so we can release one without worrying about another etc.

**Comment by zamotany** [comment]
@Krizzu definitely independenct

**Comment by grabbou** [comment]
That makes sense. My initial idea was that we have `base` one, that is used
under the hood by all the generators, but we can use `extend` functionality
of Yeoman itself?

**Comment by krizzu** [comment]
Well, there is a way of doing that, using `composeWith`
