### ISSUE TITLE
Add Husky + lint-staged into template as well

### ISSUE THREAD

**Issue by jukben** [callstack-io/generator-node-module#14]
It would be cool to option to set up a new project with Husky + lint-staged. Could be optional as well, what do you think?

cc @Krizzu @zamotany @satya164

**Comment by krizzu** [comment]
Go for it!

**Comment by zamotany** [comment]
👍 if it will be a opt-in. I'm not a fan of pre-commit hooks.

**Comment by krizzu** [comment]
I am available for questions if You'll have some

**Comment by jukben** [comment]
Ok. I'm on it. 💪
