### ISSUE TITLE
Idea: Use `licensee.js`

### ISSUE THREAD

**Issue by grabbou** [callstack-io/generator-node-module#2]
https://github.com/jslicense/licensee.js

Nice to automatically check for licenses in dependencies and generate a file that we can embed in an app or do whatever needed to stay compliant with license requirements.

**Comment by krizzu** [comment]
What licenses we should check against?

**Comment by grabbou** [comment]
We don't want to check against any licenses AFAIK. I just wanted to
generate a list of all licenses automatically to embed in the project, but
looks like the referred library does more than that.

We can close this for now I guess.

**Comment by krizzu** [comment]
http://fossa.io/
