### ISSUE TITLE
Make generator more composable

### ISSUE THREAD

**Issue by krizzu** [callstack-io/generator-node-module#4]
Hey,
The good way to approach this generator, as @grabbou said, is to make it more composable. That means to divide it into `base` generator and sub-generators. 

Base generator would include stuff that every project has (readme, gitignore, license etc.) and option to decide if it's frontend, backend or fullstack project, installing modules accordingly. 

Next, we'll give an option to extend base gene, prompting user to chose what libs to include - example: testing utils (jest/mocha), static typing (flow/typescript) etc.

That's my `vision` of how we could tackle it. Opinions are welcome :)

**Comment by zamotany** [comment]
Sounds good. Btw I don't think we need to give option to select between `jest` and `mocha`. I suggest, let's go with `jest`.

**Comment by krizzu** [comment]
#13 merged already
