### ISSUE TITLE
npm test script

### ISSUE THREAD

**Issue by rgommezz** [callstack-io/generator-node-module#6]
This issue is meant to be for discussing the possibility of tweaking some `package.json` scripts.

I suggested to use `concurrently` module for parallelising linting, flow and jest but it's true that's discouraged from the CI point of view, since it may cause some problems using the same container and the console will be mingled with outputs from the 3 processes, not following a readable order.

What about pre-commit hooks for linting and flow and leave `npm test` for just running `jest`?
I personally have hooks in my projects for that and the DX speeds up a bit every time I just wanna run tests (automatically I tend to run `npm test` rather than `npm jest`).

Also, CI builds will be faster since they will have to run unit/e2e tests only.

Let me know your thoughts.

**Comment by zamotany** [comment]
👍 for pre-commit hook

**Comment by jukben** [comment]
We have implemented optional (precommit) `lint-staged` along with `husky` so I think we could close this issue. @zamotany
